### ISSUE TITLE
NullReferenceException: at Bonobo.Git.Server.Controllers.GitController.GetInfoRefs

### ISSUE THREAD

**Issue by Excolo** [jakubgarfield/Bonobo-Git-Server#231]
I'm trying to use Bonobo with bower but I can't seem to install the repository as a bower package like this: ``` bower install http://bonobo.myserver/MyPackage.git ```

For a while nothing happens, but after some waiting I get an error stating:
```
Cloning into '.'...
fatal: http://bonobo.myserver/MyPackage.git/info/refs not valid:
is this a git repository?
```
When I check the Bonobo error logs I see the following exception:
```
w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Controllers.GitController.GetInfoRefs(String project, String service)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

I have no issues cloning the repository "manually" using just git, but whenever bower tries, it fails. I have no troubles installing bower packages from the public bower registry though.

**Comment by jakubgarfield** [comment]
It might be possible that bower is calling git clone with unsupported parameters. It needs more investigation on the client side as Bonobo doesn't support full featured git interface.

**Comment by willdean** [comment]
I don't think this is fixable now - I've tried to repro it with 3.5.0 (which is my best guess of the version the OP would have been using) and the current version of Bower (1.7.7), but I can't, and that action method is so different nowadays that this is probably not really relevant any more.

**Comment by RedX2501** [comment]
@willdean Can you retry with the latest master and if it still doesn't work we need to discuss how to proceed.

**Comment by willdean** [comment]
When I run 'bower install' against a repo through the current master of Bonobo, it does the git clone fine, which I think is where it fails for the OP.

I vote to close this - loads of reasons for a null exception in this code path have been fixed since this was reported.

**Comment by RedX2501** [comment]
@willdean Very democratic of you to vote :smile: 

@Excolo If you still experience this problem please reopen this issue.
