### ISSUE TITLE
Push fails with IsPushAuditEnabled set to True in 3.6

### ISSUE THREAD

**Issue by kholme2** [jakubgarfield/Bonobo-Git-Server#258]
With push auditing enabled push failed with the following errors:

Client:
Counting objects: 9, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 343 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
fatal: protocol error: bad line length character: <!DO
fatal: The remote end hung up unexpectedly

Server:
w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.NotSupportedException: Specified method is not supported.
   at System.Web.HttpBufferlessInputStream.Seek(Int64 offset, SeekOrigin origin)
   at Bonobo.Git.Server.Git.GitService.ReceivePackHook.ReceivePackParser.ExecuteServiceByName(String correlationId, String repositoryName, String serviceName, ExecutionOptions options, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Git.GitService.ReceivePackHook.Durability.DurableGitServiceResult.ExecuteServiceByName(String correlationId, String repositoryName, String serviceName, ExecutionOptions options, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Git.GitService.GitServiceExtensions.ExecuteGitReceivePack(IGitService self, String correlationId, String repositoryName, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Controllers.GitController.<>c__DisplayClass2.<ExecuteReceivePack>b__0(Stream outStream)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by jakubgarfield** [comment]
I remember reverting part of the functionality from the project. Damn you Liskov principle violation on Stream decendants!

@stanshillis are you having luck with running this feature in production?

**Comment by stanshillis** [comment]
I'm running it in prod actually and haven't had this come up. It does
happen on a non-code related project and that computer is running a
different version of git client i believe. But i haven't had time to
investigate it.

**Comment by RedX2501** [comment]
I assume this got fixed as we have not heard anything else from you.
If the problem persists please reopen.
