### ISSUE TITLE
Occasional Error on Push - Session state has created a session id, but cannot save it because the response was already flushed by the application.

### ISSUE THREAD

**Issue by jhudsonWA** [jakubgarfield/Bonobo-Git-Server#310]
Every couple of hours we get an error on push. The files seem to make it the server fine, as we can see them in the commit but we get a response like:

git push
Username for 'xxxxxxxx': 
Password for 'xxxxxxxxx':
fatal: protocol error: bad line length character: <!DO
Counting objects: 907, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (546/546), done.
Writing objects: 100% (907/907), 4.11 MiB | 7.23 MiB/s, done.
Total 907 (delta 360), reused 862 (delta 344)
fatal: The remote end hung up unexpectedly
fatal: write error: Invalid argument
error: failed to push some refs to 'http://xxx.xxxxxxxx/xxxxx.git'
The x's are just me hiding internal server data.

The error logged in the Bonobo error log is:

w3wp.exe Error: 0 : Server Error occured and caught in Global.asax - System.Web.HttpException (0x80004005): Session state has created a session id, but cannot save it because the response was already flushed by the application.
   at System.Web.SessionState.SessionIDManager.SaveSessionID(HttpContext context, String id, Boolean& redirected, Boolean& cookieAdded)
   at System.Web.SessionState.SessionStateModule.DelayedGetSessionId()
   at System.Web.SessionState.SessionStateModule.ReleaseStateGetSessionID()
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Windows Server 2008

**Comment by jhudsonWA** [comment]
i should note, we can cause this every time by doing a iisrestart, waiting a few minutes and then doing a push. The first person who hits gets this error. Will also fire if the app pool ever recycles.

**Comment by jhudsonWA** [comment]
Any feedback on this issue? We can always do a pull if a git pull/push has not happened for 20 minutes or so, but it's annoying at best.

**Comment by RedX2501** [comment]
What version did this happen on? Does this still happen with 5.1.1? What are your configurations? CookieAuth with InternalDB?

**Comment by jhudsonWA** [comment]
This was 4.0. We are using it in an enterprise environment and have not had
a chance to upgrade to latest. Once we do in the next month I'll update
this issue.

**Comment by JasonVKGE** [comment]
I'm experiencing a similar issue.

Configuration:
  Bonobo: 6.2.1.588
  Windows Server: 2012R2 (Version 6.3 Build 9600)
  IIS: 8.5.9600.16384
  Bonobo configuration:
    <add key="AuthenticationProvider" value="Windows" />
    <add key="MembershipService" value="ActiveDirectory" />

Steps to reproduce seem to be:

1) Do a iisresetart, wait a few minutes.
2) git pull.

I'll try to investigate further when I have time.

[Log_files.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/1569037/Log_files.txt)

**Comment by JasonVKGE** [comment]
I changed the setting for "Anonymous" to "No" and my issue has gone away.
