### ISSUE TITLE
Clone error with v4.0

### ISSUE THREAD

**Issue by salimoneus** [jakubgarfield/Bonobo-Git-Server#326]
Recently performed an upgrade from last release to the current release (v4.0), and everything seemed to be working (thanks for shallow clone fix!), except I noticed that Bonobo was crashing when trying to Clone a repo using the web interface.

Firstly, does the upgrade process basically consist of copying and over-writing all the existing app files?  Want to check and make sure something didn't go awry there.  I didn't personally do the upgrade but that is my understanding of how it was done.

The error seems to happen with old accounts, new accounts, and admin accounts.  Also tried various repos and was getting the error.

Here's the website error message:

An Error Occurred
An error occurred when processing your request. Please try again or contact the system administrator.

Here is the log output:

Native library pre-loader is trying to load native SQLite library "C:\MelcoApps\Git\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Controllers.RepositoryController.ConvertRepositoryDetailModel(RepositoryDetailModel model)
   at Bonobo.Git.Server.Controllers.RepositoryController.Clone(String id, RepositoryDetailModel model)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by latop2604** [comment]
This issue was already reported and fixed (#292) but after 4.0 release

**Comment by salimoneus** [comment]
Ok, I must have missed it in the issues list.  Thanks!
