### ISSUE TITLE
AD Install loses repo settings in upgrade from 5.2 to 6.0 pre-release

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#602]
In #587 @Trapulo posted 

> @willdean tried to update to last build. Lost every repo details (users permissions, logos, and other details) but all seems ok. Tried a little sync and commit from Visual Studio and all seems ok. Is there some specific trouble may I search?

@Trapulo, assuming you have a backup copy of your old 5.2 install, could you see if you have an "ADBackend" directory in app_data for both 5.2 and 6.0 installs, and if you can see any obvious difference between the files in the "Repos" subdirectory in both installs.

I don't think it should have lost all your repo settings on that upgrade.

**Comment by Trapulo** [comment]
Yes, I have ADBackend in both. Folder structure is same. Files seem same. The only difference is in \Users, where I found two file in the new, and just one (fine different guid-name) in the old one.

The old one contains data for an "Administrator" user with two domain members. The new one contains a different file for same two domain users. I think you changed something in user management and seems ok.

**Comment by willdean** [comment]
@trapulo It looks like losing all your settings on an upgrade might be a duplicate of this issue: #580

I'm going to try and test this here, but if you're able to go back to your 5.2 installation, could you try upgrading from 5.2 to this version here: https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/437/artifacts and see if all your settings are preserved.  Thanks.

**Comment by Trapulo** [comment]
@willdean I tried, still all repos are cleared. Descriptions = "Description Discovered in file system. "

Maybe I make something wrong during upgrade?

**Comment by willdean** [comment]
@Trapulo Thanks very much for trying - could you please try again with this version: https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/455/artifacts which has some changes in that I made last night.

It's not anything you're doing wrong - it needs to just work.

**Comment by willdean** [comment]
@Trapulo Please disregard the link above, I've merged the code into the master branch, so could you please try https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/artifacts instead.  Thanks.

**Comment by Trapulo** [comment]
@willdean mmmm is didn't create Roles and Repos folders under app_data\AdBackend.
Manually creating them, it starts but repo list is empty

**Comment by willdean** [comment]
@Trapulo - thanks very much for trying this - there must have been some failure early during the update - can you see if there is an exception stack trace in the error log in \app_data?

**Comment by Trapulo** [comment]
w3wp.exe Error: 0 : Server Error occured and caught in Global.asax - System.Web.HttpException (0x80070006): The remote host closed the connection. The error code is 0x80070006.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at Bonobo.Git.Server.Git.GitService.GitServiceExecutor.ExecuteServiceByName(String correlationId, String repositoryName, String serviceName, ExecutionOptions options, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Git.GitService.GitServiceExtensions.ExecuteGitUploadPack(IGitService self, String correlationId, String repositoryName, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Controllers.GitController.<>c__DisplayClass12_0.<ExecuteUploadPack>b__0(Stream outStream)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by willdean** [comment]
@Trapulo Thanks for that - that's some kind of error during a Git call - it's not related to this update.  A relevant update exception would have UpdateADBackend somewhere in the stack.  

I guess we just need to make the update much more robust, so that it can carry on even if it has problems with a specific role/team/whatever.  Then we could narrow down what's actually breaking in your case.  Thanks for your continued help on this - I'll let you know if/when there's a new version to try.

**Comment by larshg** [comment]
Hey @willdean 

I just tried to update to the newest master and found out that we are aquiring the domain name by asuming its the same as what is after the @ in the mail address. However this is atleast no the case here, where the AD server is set up running a local domain name of drs.lan - but also handles the danrobotics.dk name. Unfortunately we can't create a PrincipalContext using the last name, so a LDAP-server is not available Exception is thrown when updating the users - hence the Teams, roles and repos is never updated.

A solution could be to make seperat method to extract the domain from mail, if it fails to create the princpalContext, fallback to the ActivedirectorySettings.DefaultDomain - or just use the DefaultDomain directly?

Regards Lars

**Comment by larshg** [comment]
I just noticed that teams are added twice, because when upgrading there are just assigned a new guid instead of fetching the one from AD. But I'm out of time for now to do something about it.

**Comment by willdean** [comment]
@Trapulo Would you be available to test this again using the artifacts from PR #637 (You can get the build from here: https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/494 )

@larshg Has done a bunch of work on the import which might make your situation work again, and we're really struggling to test this widely.

**Comment by Trapulo** [comment]
Sorry, I deleted old setup 5.x.. :(
