### ISSUE TITLE
Visual Studio 2015 Update 3 Error :  Found invalid hex digit in length

### ISSUE THREAD

**Issue by babakjahangiri** [jakubgarfield/Bonobo-Git-Server#649]
When I decide to published the first fresh and default project to my server  i got this error 
: "Found invalid hex digit in length" 

Server Machine : Windows Server 2008 R ,Client Side :  Visual Studio 2005 U3 , default & empty web solution

I tried different origin link such as below but error still there ...
http://user:password@mydomain.com/myrepo.git
http://user@mydomain.com/myrepo.git

I checked the log belong to this error and it was this : 

w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecute>b__14(AsyncCallback asyncCallback, Object callbackState, Controller controller)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by willdean** [comment]
Can you try this version, please and see it fixes your problem: https://ci.appveyor.com/api/buildjobs/1xlle33tpiq2xha5/artifacts/bonobo-git-server-7265243-ffbbb5e8093028ebe5842e8a5a73ac21ce12b612.zip

**Comment by babakjahangiri** [comment]
Thank you for your replay willdean , I install this one , it seems to be work until the host machine request me credential so I make a user and grant access for whole holder of the web site , but it still ask for credential . I input my user name such as this  : HostMachineName\USERNAME    & Password  

the log file error is :

`Native library pre-loader is trying to load native SQLite library "C:\HostingSpaces\git.mysite.com\wwwroot\bin\x86\SQLite.Interop.dll"...`

**I think my problem is now verification & validation because I do not know on which folder should I grand the permission and what Group of user should have this permission !**

**Comment by willdean** [comment]
That message is not an error - it's just something the SQLLite library writes to the log file.

I'm afraid I'm not clear if you're having problems using a Git client or if you're having problems going to Bonobo with a web-browser.

If you can start a browser *ON YOUR BONOBO SERVER*, you should be able to go to http://<my server>/home/diagnostics and get a diagnostics page which might help me help you.

If you get asked for credentials when you go to that page, then you have not configured IIS correctly.

**Comment by babakjahangiri** [comment]
> I'm afraid I'm not clear if you're having problems using a Git client or if you're having problems going to Bonobo with a web-browser


Actually my problem is not on bonboo with a web-browser 
My problem appear when I want to publish my files through Visual Studio 2015 u3  to the server , files are not copied and the windows Security message box is showing to me and ask me enter credential for access to web site . 
 
I don't know which username and password should I type , I tried Internal Membership password , I make a user on my server with full permission on web site , but none of these not worked for me . 

this is the content of diagnostic page which you wanted from me , please check below parameters , if you think i made a wrong please correct for me .

Web.Config AppSettings
--AppSettings.webpages:Enabled: 'false'
--AppSettings.ClientValidationEnabled: 'true'
--AppSettings.UnobtrusiveJavaScriptEnabled: 'true'
--AppSettings.UserConfiguration: '~\App_Data\config.xml'
--AppSettings.DefaultRepositoriesDirectory: '~\App_Data\Repositories'
--AppSettings.GitPath: '~\App_Data\Git\git.exe'
--AppSettings.GitHomePath: '~\App_Data'
--AppSettings.RecoveryDataPath: '~\App_Data\Recovery'
--AppSettings.AuthenticationProvider: 'Cookies'
--AppSettings.ImportWindowsAuthUsersAsAdmin: 'false'
--AppSettings.MembershipService: 'Internal'
User Configuration:
--User config file: 'C:\HostingSpaces\mysite.com\wwwroot\App_Data\config.xml'
--User config readable: OK
--User config saveable: OK
--User config folder: Exists, 6 files, 8 entries, writeable
Repo Directory
--Configured repo path: '~\App_Data\Repositories'
--Effective repo path: 'C:\HostingSpaces\mysite.com\wwwroot\App_Data\Repositories'
--Repo dir: Exists, 1 files, 2 entries, writeable
Git Exe
--Git path: 'C:\HostingSpaces\mysite.com\wwwroot\App_Data\Git\git.exe'
--Git.exe exists: OK
Federated Authentication
--Not Enabled: 
Active Directory
--Not Enabled
Internal Membership
--User count: 2

**Comment by willdean** [comment]
If you've made a user in Bonobo using the Bonobo web interface called "MyUserName", with a password "Password", then when you get asked for credentials by Visual studio, you should just enter MyUserName and Password - you should not do anything like `HostMachineName\USERNAME`.

You should tell VS that your URL is something like `http://mydomain.com/myrepo.git` - don't bother with the URLs which have usernames in.

**Comment by babakjahangiri** [comment]
Thank you for your comment ,My Problem has solved 
My Problem was in IIS   Authentication , When I got the error I had enabled the basic Authentication in IIS . 

Could you please tell me whats is different  between below url which are mentioned in web interface of Bonobo Git server  :

http://username@mydomain.com/myproject.git   
and 
http://mydomain.com/myproject.git

**Comment by willdean** [comment]
The top one is for situations where you want to be able to connect to the same repository but with different user credentials.

Personally I've never needed to use one - I always use the second kind.
