### ISSUE TITLE
Repository URL does not work

### ISSUE THREAD

**Issue by jannemec** [jakubgarfield/Bonobo-Git-Server#659]
Hi, I installed clear installation on W2012R2 IIS server (http://intranet/), creation of repository is without problem, the url on the repository http://intranet/Bonobo.Git.Server/Repository/intranet works correctly, but any attempt to go to url "General url" : "http://intranet/Bonobo.Git.Server/intranet.git" shows error 404 and in the IIS log there is row
2017-03-29 16:23:39 192.168.10.136 GET /Bonobo.Git.Server/intranet.git - 80 Jan+Němec 192.168.8.48 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/56.0.2924.87+Safari/537.36 http://intranet/Bonobo.Git.Server/Repository/intranet 200 0 0 0

I have no clue where to search another log error

**Comment by willdean** [comment]
You should not browse to the xxxxxx.git URL - it's just for use with Git clients.

**Comment by holiiveira** [comment]
This URL is for use on Git clients, not accessed via browser.

**Comment by huchim** [comment]
I'm having the same problem:

>git clone http://10.66.8.115/CEFAG.git de
Cloning into 'de'...
fatal: unable to access 'http://10.66.8.115/CEFAG.git/': The requested URL returned error: 403

I copy the app into wwwrooot (i tried to with wwwroot\Bonobo\ "http://10.66.8.115/bonobo/CEFAG.git/")

Bonobo versión 6.0
IIS 7.5

**Comment by willdean** [comment]
@huchim That's not the same problem - the OP is browsing to the Git URL and getting a 404 - you're using a Git client and getting a 403 error which is some kind of permissions problem.

Can you get to any of the Bonobo pages with a browser?

**Comment by huchim** [comment]
Ops! That's true :smile: 

I can access any pages in the browser (including http://10.66.8.115/Repository/Detail/25e99306-2e6b-44e0-b5ca-da2f928063de) ...

**Comment by holiiveira** [comment]
Make sure it is not some proxy setting.

**Comment by willdean** [comment]
Do you have any kind of cached credentials at the client?

Try running `set GIT_TRACE_CURL=true` at the command line before the `git clone` and have a good look through the resulting trace to see if you can see what's happening.

**Comment by huchim** [comment]
Thanks @willdean, after using the variable `GIT_TRACE_CURL` I could see that the problem as as @holiiveira said me.

Thank you so much guys!

I used the variable `NO_PROXY=10.66.8.115` in order to bypass my proxy.

**Comment by jannemec** [comment]
Well, I tried the web gui client and pushed the repository with following result:
fatal: http://intranet/Bonobo.Git.Server/intranet.git/info/refs not valid: is this a git repository?
Pushing to http://intranet/Bonobo.Git.Server/intranet.git

and server log shows
2017-03-31 05:16:24 192.168.10.136 GET /Bonobo.Git.Server/intranet.git/info/refs service=git-receive-pack 80 - 192.168.8.48 git/2.11.0.windows.1 - 401 0 0 15
2017-03-31 05:16:24 192.168.10.136 GET /Bonobo.Git.Server/intranet.git/info/refs service=git-receive-pack 80 - 192.168.8.48 git/2.11.0.windows.1 - 401 0 0 0
2017-03-31 05:16:24 192.168.10.136 GET /Bonobo.Git.Server/intranet.git/info/refs service=git-receive-pack 80 OTK\u935 192.168.8.48 git/2.11.0.windows.1 - 200 0 0 15

**Comment by willdean** [comment]
@jannemec Do you really have a repository called 'intranet'?

I'm not really clear all the different things you've tried, but I'd suggest the following:

* Make sure you're using Bonobo 6.0
* Use the web interface to create a new repository
* On the repository's page in the Bonobo web interface, there's a 'Git URL' with a copy button next to it
* Start a command line and enter `set GIT_TRACE_CURL=true`
* At the command line enter `git clone <Git URL from the repository page>`

**Comment by jannemec** [comment]
@willdean yea I do have - I tried to reinstall bonobo git server - after some time (I hade to manualy download the the repository (I renamed to otk) and cloned it but for each push I get error 500 and on the server is  log message
2017-04-03 07:27:35 192.168.10.136 GET /Bonobo.Git.Server/otk.git/info/refs service=git-receive-pack 80 OTK\u935 192.168.8.48 git/2.11.0.windows.1 - 500 0 64 15

**Comment by jannemec** [comment]
BTW cloning of repository shows following message
$ git clone http://intranet/Bonobo.Git.Server/otk.git
Cloning into 'otk'...
warning: You appear to have cloned an empty repository.
and downloaded empty repository returns zip that cannot be opened - zip error

**Comment by willdean** [comment]
@jannemec If you're running Bonobo 6.0, you can start a browser *on the server* and go to http://<server>/home/diagnostics - this will give you/us some diagnostic information including a recent part of the Bonobo error log, which might help see what's going on.

You should also follow my instructions about `set GIT_TRACE_CURL=true` to you can see what's happening on the client.

**Comment by jannemec** [comment]
Web.Config AppSettings
--AppSettings.webpages:Enabled: 'false'
--AppSettings.ClientValidationEnabled: 'true'
--AppSettings.UnobtrusiveJavaScriptEnabled: 'true'
--AppSettings.UserConfiguration: '~\App_Data\config.xml'
--AppSettings.DefaultRepositoriesDirectory: '~\App_Data\Repositories'
--AppSettings.GitPath: '~\App_Data\Git\git.exe'
--AppSettings.GitHomePath: '~\App_Data'
--AppSettings.RecoveryDataPath: '~\App_Data\Recovery'
--AppSettings.AuthenticationProvider: 'Cookies'
--AppSettings.ImportWindowsAuthUsersAsAdmin: 'false'
--AppSettings.MembershipService: 'Internal'
User Configuration:
--User config file: 'C:\inetpub\intranet\Bonobo.Git.Server\App_Data\config.xml'
--User config readable: OK
--User config saveable: OK
--User config folder: Exists, 5 files, 7 entries, writeable
Repo Directory
--Configured repo path: '~\App_Data\Repositories'
--Effective repo path: 'C:\inetpub\intranet\Bonobo.Git.Server\App_Data\Repositories'
--Repo dir: Exists, 1 files, 3 entries, writeable
Git Exe
--Git path: 'C:\inetpub\intranet\Bonobo.Git.Server\App_Data\Git\git.exe'
--Git.exe exists: OK
Federated Authentication
--Not Enabled: 
Active Directory
--Not Enabled
Internal Membership
--User count: 4
**********************************************************************************
Exception Log
--LogFileName: : C:\inetpub\intranet\Bonobo.Git.Server\App_Data\Bonobo.Git.Server.Errors.log
--Log File total length: 56801
--Starting log dump from : 46801
angeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\intranet\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : 04/03/2017 14:11:04: Error caught in GitController System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Controllers.GitController.GetInfoRefs(String repositoryName, String service)
   at Bonobo.Git.Server.Controllers.GitController.SecureGetInfoRefs(String repositoryName, String service)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
w3wp.exe Error: 0 : 04/03/2017 14:12:35: Error caught in GitController System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Controllers.GitController.GetInfoRefs(String repositoryName, String service)
   at Bonobo.Git.Server.Controllers.GitController.SecureGetInfoRefs(String repositoryName, String service)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\intranet\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : 04/03/2017 14:18:31: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\intranet\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : 04/03/2017 15:13:09: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
w3wp.exe Error: 0 : 04/03/2017 15:20:39: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
w3wp.exe Error: 0 : 04/03/2017 15:21:47: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
w3wp.exe Error: 0 : 04/03/2017 15:26:55: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\intranet\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...
w3wp.exe Error: 0 : 04/03/2017 15:31:34: Error caught in GitController System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
Native library pre-loader is trying to load native SQLite library "C:\inetpub\intranet\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll"...

**Comment by larshg** [comment]
> $ git clone http://intranet/Bonobo.Git.Server/otk.git
> Cloning into 'otk'...
> warning: You appear to have cloned an empty repository.

this warning is only a .... warning - and is expected, so it seems that you successfully cloned the empty repository? Does the folder contiain a .git folder (normally hidden) ?

About downloading a empty repository, it works fine here - using winrar to browse the zip file.

Are there any special characters in the username or password? Because it seems it fails to split the 64based encoded string which contains the supplied password and username.

What client is used? and do you enter credentials? Are you using any special characters(this shouldn't result in the argumentOutOfRangeException)

**Comment by willdean** [comment]
@jannemec - Thanks for posting that - as @larshg says, there is something wrong with the way your client is trying to authenticate.

**Comment by jannemec** [comment]
@larshg  I confirm downloaded zip can be opened by winrar.
And you are right (at least I hope so) the problem is with authentication. I am using on windows 10 git 2.12.2 from git-scm.com - 64bit version
When I allowed anonymous push,, I was able to push repository to server
I can live with anonymous push (its intranet site), but I have no idea why the authentication failed.

**Comment by larshg** [comment]
Are you just using git bash?

**Comment by jannemec** [comment]
And BTW, thank you all very much for this product and support.

**Comment by jannemec** [comment]
@larshg yes i use git bash, I tried even gui and git from Netbeans environment - all same result, From git bash there was prompt for username and password - and authentication error for 1. attempt, error 500 for second attempt.

**Comment by larshg** [comment]
@jannemec does it fail if you use the default admin user?

How is the IIS setup with authentication?

Alternatively can you try clone bonobo and run it in debug yourself? It will launch a standard site where you can try create a repository at see if you can clone / push to this? And maybe set a breakpoint [here](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Attributes/GitAuthorizeAttribute.cs#L88) ?

**Comment by mlarizzate** [comment]
Hi guys, i'm having the same problem

![image](https://user-images.githubusercontent.com/1816228/41553778-2e1b2b52-7309-11e8-9730-4b792643b1fe.png)
