### ISSUE TITLE
Adding team causes System.NullReferenceException in 6.1.0...

### ISSUE THREAD

**Issue by storaid** [jakubgarfield/Bonobo-Git-Server#685]
previous version v5.2 is working fine for team...
but new version is not good...
I got the following error:
[Error] Exception caught in Global.asax1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Data.ADTeamRepository.<>c__DisplayClass6_0.<GetTeams>b__1(UserModel y)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Bonobo.Git.Server.Security.RepositoryPermissionService.GetAllPermittedRepositories(Guid userId, RepositoryAccessLevel requiredLevel)
   at Bonobo.Git.Server.Attributes.AllViewsFilter.PopulateRepoGoToList(Guid id, ControllerContext ControllerContext)
   at Bonobo.Git.Server.Attributes.AllViewsFilter.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__31(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters, AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

here is my config:
    <add key="AuthenticationProvider" value="Windows" />

    <add key="ImportWindowsAuthUsersAsAdmin" value="false" />
    
    
    <add key="MembershipService" value="ActiveDirectory" />
	
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="GitUsers" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=GitDevelopers" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />

**Comment by willdean** [comment]
Thanks for reporting this - would you mind installing the version from here:

https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/566/artifacts

and then please look in the new log files in app_data\logs and see if there's anything there which points us closer to the problem?

**Comment by storaid** [comment]
hello, still got the same error:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bonobo.Git.Server.Data.ADTeamRepository.<>c__DisplayClass6_0.<GetTeams>b__1(UserModel y)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Bonobo.Git.Server.Security.RepositoryPermissionService.GetAllPermittedRepositories(Guid userId, RepositoryAccessLevel requiredLevel)
   at Bonobo.Git.Server.Attributes.AllViewsFilter.PopulateRepoGoToList(Guid id, ControllerContext ControllerContext)
   at Bonobo.Git.Server.Attributes.AllViewsFilter.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__31(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters, AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

my config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    
  </configSections>
  <appSettings>
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="UserConfiguration" value="~\App_Data\config.xml" />
    <add key="DefaultRepositoriesDirectory" value="~\App_Data\Repositories" />
    <add key="GitPath" value="~\App_Data\Git\git.exe" />
    <add key="GitHomePath" value="~\App_Data" />
    <add key="RecoveryDataPath" value="~\App_Data\Recovery" />
    <add key="LogDirectory" value="~\App_Data\Logs" />
    <add key="serilog:minimum-level" value="Information" />
    
    
    
    
    <add key="AuthenticationProvider" value="Windows" />

    <add key="ImportWindowsAuthUsersAsAdmin" value="false" />
    
    
    <add key="MembershipService" value="ActiveDirectory" />

    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="GitUsers" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=GitDevelopers" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />
    
  </appSettings>
  <connectionStrings>
    
    <add name="BonoboGitServerContext" connectionString="Server=DB1.STORAID.LOCAL;Database=bonobogit;Integrated Security=True;" providerName="System.Data.SqlClient" />
  </connectionStrings>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="errorListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="App_Data/Bonobo.Git.Server.Errors.log" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
  
  <system.web>
    <globalization enableClientBasedCulture="true" uiCulture="auto" />
    <customErrors mode="On" defaultRedirect="Home/Error" />
    <httpRuntime maxRequestLength="102400" />
    <authentication mode="None" />
    <compilation debug="true" targetFramework="4.6" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="RoleManager" />
    </modules>
    <handlers>
      <remove name="UrlRoutingHandler" />
    </handlers>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="104857600" />
        <fileExtensions allowUnlisted="true">
          <clear />
        </fileExtensions>
        <hiddenSegments>
          <clear />
        </hiddenSegments>
      </requestFiltering>
    </security>
    <staticContent>
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
    </staticContent>
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Antlr3.Runtime" publicKeyToken="eb42632606e9261f" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.1.3.0" newVersion="5.1.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocol.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.40306.1554" newVersion="1.0.40306.1554" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Data.SQLite" publicKeyToken="db937bc2d44ff139" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.104.0" newVersion="1.0.104.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="Data Source=.; Integrated Security=True; MultipleActiveResultSets=True" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <clear />
    <remove invariant="System.Data.SQLite.EF6" /><add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" /><remove invariant="System.Data.SQLite" /><add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" /></DbProviderFactories>
  </system.data>
</configuration>

my ad groups:
![201705030806](https://cloud.githubusercontent.com/assets/25889706/25644288/8ad4264e-2fd7-11e7-89c4-6917ea807f6e.jpg)

**Comment by larshg** [comment]
Can you verify that all users that are in either gitDevelopers or GitAdmins is also in GitUsers?

**Comment by larshg** [comment]
Can try out (this)[https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/567/artifacts] when its complete?

That should handle the error - but it is also using a new way to get info from AD - which would be nice if you could test this too!

Remember backup of your repositories etc.

**Comment by storaid** [comment]
"Can try out this when its complete?"
this build has resolved my problem...
now is working fine for team function...
thx very much for your help...
2017-05-03 16:57:37.038 +08:00 [Information] Bonobo starting
2017-05-03 16:57:39.210 +08:00 [Information] Searching in 2 global catalogs
2017-05-03 16:57:39.226 +08:00 [Information] Searching for user in globalcatalog "DC1.STORAID.LOCAL" in domain "STORAID.LOCAL"
2017-05-03 16:57:39.851 +08:00 [Information] Searching in 2 global catalogs
2017-05-03 16:57:39.867 +08:00 [Information] Searching for user in globalcatalog "DC1.STORAID.LOCAL" in domain "STORAID.LOCAL"
2017-05-03 16:57:39.992 +08:00 [Information] Searching in 2 global catalogs
2017-05-03 16:57:40.007 +08:00 [Information] Searching for user in globalcatalog "DC1.STORAID.LOCAL" in domain "STORAID.LOCAL"

![201705031702](https://cloud.githubusercontent.com/assets/25889706/25654098/65789510-3022-11e7-90db-d275596c28f5.jpg)
