### ISSUE TITLE
Can't create repository

### ISSUE THREAD

**Issue by ceeroshelter** [jakubgarfield/Bonobo-Git-Server#728]
When clicking Create new repository in the web GUI, I get:

An Error Occurred
An error occurred when processing your request. Please try again or contact the system administrator.

From the log:

2017-08-18 10:45:29.591 +02:00 [Error] Exception caught in Global.asax1
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , UserModel )
   at MvcCheckBoxList.Library.ListBuilder.<>c__DisplayClass1`4.<_listBuilder>b__0(TItem s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MvcCheckBoxList.Library.ListBuilder._listBuilder[TModel,TItem,TValue,TKey](HtmlHelper`1 htmlHelper, ModelMetadata modelMetadata, String listName, Expression`1 sourceDataExpr, Expression`1 valueExpr, Expression`1 textToDisplayExpr, Expression`1 htmlAttributesExpr, Expression`1 selectedValuesExpr, Expression`1 selectedValueExpr, Object htmlAttributes, HtmlListInfo htmlListInfo, String[] disabledValues, Position position)
   at MvcCheckBoxList.Library.ListBuilder.CheckBoxList[TModel,TItem,TValue,TKey](listConstructor`4 lc)
   at Extensions.CheckBoxListFor[TModel,TProperty,TItem,TValue,TKey](HtmlHelper`1 htmlHelper, Expression`1 listNameExpr, Expression`1 sourceDataExpr, Expression`1 valueExpr, Expression`1 textToDisplayExpr, Expression`1 selectedValuesExpr, Position position)
   at ASP._Page_Views_Repository_Create_cshtml.Execute()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by ceeroshelter** [comment]
Aaaand of course, right after I post that, I figure it out.

I had to go to advanced settings for the application pool and enable 32-bit applications.
