### ISSUE TITLE
unable to access git repository: The requested URL returned error: 500

### ISSUE THREAD

**Issue by frunta** [jakubgarfield/Bonobo-Git-Server#751]
Dears,
  I've successfully 'installed' bonobo Git Server, logged in, created a repository (TEST). Everything went well. But when I want to clone repository using repository URL generated by Bonobo, following error occurs:

```
git.exe clone --progress -v "http://git.myserver.com/TEST.git" "W:\gitrep\TEST"

Cloning into 'W:\gitrep\TEST'...
unable to access 'http://git.myserver.com/TEST.git/': The requested URL returned error: 500
**git did not exit cleanly (exit code 128) (656 ms @ 17. 10. 2017 23:07:11)**
```

Bonobo log file contains exactly the same trace as described in #214 issue.

Restart/recycle app pool does not solve it. I've tried anonymous access also.

Bonobo Git server seems to me be a perfect IIS alternative to Linux version.

Thanks a lot,
Frunta.

```
Error caught in GitController
System.Web.HttpException (0x80004005): This method or property is not supported after HttpRequest.Form, Files, InputStream, or BinaryRead has been invoked.
   at System.Web.HttpRequest.GetInputStream(Boolean persistEntityBody, Boolean disableMaxRequestLength)
   at System.Web.HttpRequestWrapper.GetBufferedInputStream()
   at Bonobo.Git.Server.Controllers.GitController.GetInputStream(Boolean disableBuffer)
   at Bonobo.Git.Server.Controllers.GitController.<>c__DisplayClass23_0.<GetInfoRefs>b__0(Stream outStream)
   at Bonobo.Git.Server.Git.GitCmdResult.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
```

**Comment by willdean** [comment]
Thanks for this - I don't really think the situation can be exactly what's implied by the message with the exception, because if we were opening streams in an illegal order then this problem would be much more widespread.

On this SO question: https://stackoverflow.com/questions/17602845 there are some answers where people say that in fact the problem was caused by other things, like a request being too large for maxRequestLength.    This seems unlikely when you've just created a repo, but I do wonder if there's something unusual about the way that Git is running on your server which is causing something odd about the way this request is being handled.

I'm not sure what to suggest right now.

**Comment by venkatasurendra1** [comment]
i am facing this issue 

Permission to syndicatetechltd/venkata.git denied to venkatasurendra1.
fatal: unable to access 'https://github.com/syndicatetechltd/venkata.git/': The requested URL returned error: 403
