### ISSUE TITLE
The requested URL returned error: 500 when trying to push

### ISSUE THREAD

**Issue by jbdicarlo** [jakubgarfield/Bonobo-Git-Server#762]
When trying to push my code into an empty repo, I get "Error: fatal: unable to access 'http://user%40domain:***@web-server/Bonobo.Git.Server/Dashboard_FrontEnd.git/': The requested URL returned error: 500" (user, domain and web-server used in place of redacted info).

I've checked all the possible GitHub open/closed issues, Google searches and other resources I can find for the past hour and have had no luck. This is not related to the 500.19 issue getting the IIS server error.

Any help would be greatly appreciated as I'm currently at a loss.

````````Web.Config AppSettings
--AppSettings.webpages:Enabled: 'false'
--AppSettings.ClientValidationEnabled: 'true'
--AppSettings.UnobtrusiveJavaScriptEnabled: 'true'
--AppSettings.UserConfiguration: '~\App_Data\config.xml'
--AppSettings.DefaultRepositoriesDirectory: '~\App_Data\Repositories'
--AppSettings.GitPath: '~\App_Data\Git\git.exe'
--AppSettings.GitHomePath: '~\App_Data'
--AppSettings.RecoveryDataPath: '~\App_Data\Recovery'
--AppSettings.LogDirectory: '~\App_Data\Logs'
--AppSettings.serilog:minimum-level: 'Information'
--AppSettings.AuthenticationProvider: 'Cookies'
--AppSettings.ImportWindowsAuthUsersAsAdmin: 'false'
--AppSettings.MembershipService: 'ActiveDirectory'
--AppSettings.ActiveDirectoryDefaultDomain: 'domain.com'
--AppSettings.ActiveDirectoryBackendPath: '~\App_Data\ADBackend'
--AppSettings.ActiveDirectoryMemberGroupName: 'MemberGroup'
--AppSettings.ActiveDirectoryRoleMapping: 'Administrator=Admin group'
User Configuration:
--User config file: 'C:\inetpub\wwwroot\Bonobo.Git.Server\App_Data\config.xml'
--User config readable: OK
--User config saveable: OK
--User config folder: Exists, 4 files, 8 entries, writeable
Repo Directory
--Configured repo path: '~\App_Data\Repositories'
--Effective repo path: 'C:\inetpub\wwwroot\Bonobo.Git.Server\App_Data\Repositories'
--Repo dir: Exists, 1 files, 2 entries, writeable
Git Exe
--Git path: 'C:\inetpub\wwwroot\Bonobo.Git.Server\App_Data\Git\git.exe'
--Git.exe exists: OK
Federated Authentication
--Not Enabled: 
Active Directory
--Backend folder exists: OK
--Backend folder: Exists, 0 files, 4 entries, writeable
--User count: 28
AD Teams
AD Roles
--Administrator: 10 members
Internal Membership
--Not Enabled
**********************************************************************************
Exception Log
--LogFileName: : C:\inetpub\wwwroot\Bonobo.Git.Server\App_Data\Logs\log-20171119.txt
--Log File total length: 554105
--Starting log dump from : 544105
ainName)
2017-11-19 11:04:27.456 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.487 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.519 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.551 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.599 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.614 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.645 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.676 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.692 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.723 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.755 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.770 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.801 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.833 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.848 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.880 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.911 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.942 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.958 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:27.989 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:28.020 -05:00 [Error] Failed to create Directory context for domain "emaildomain.org".
System.DirectoryServices.ActiveDirectory.ActiveDirectoryObjectNotFoundException: The specified domain does not exist or cannot be contacted.
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Bonobo.Git.Server.Helpers.ADHelper.GetDomain(String parsedDomainName)
2017-11-19 11:04:28.117 -05:00 [Information] Searching for group "TSC_Support group" in domain "domain.com"
2017-11-19 11:05:02.447 -05:00 [Warning] GitAuth: No auth header, anon operations not allowed
2017-11-19 11:05:02.447 -05:00 [Warning] GitAuth: No auth header, anon operations not allowed
2017-11-19 11:05:02.478 -05:00 [Error] Error caught in GitController
System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

**Comment by willdean** [comment]
Are you able to try using a URL without the username embedded in it - e.g. http://web-server/Bonobo.Git.Server/Dashboard_FrontEnd.git ?

(Then provide the username / password through the Git client. )

If this works, then that's a useful datapoint for us.

**Comment by jbdicarlo** [comment]
> Are you able to try using a URL without the username embedded in it - e.g. http://web-server/Bonobo.Git.Server/Dashboard_FrontEnd.git ?

Unfortunately no, neither URL work.

I've received a slightly more specific error this time around though from a different context. Neither URL works in either context but I get the error 500 from Brackets (the editor I'm using to write the code being pushed to my repo) which is using git.exe. When trying to do it from Git Bash I get "fatal: Authentication failed for ''http://web-server/Bonobo.Git.Server/Dashboard_FrontEnd.git'" I also get this when trying to use the embedded username URL.

**Comment by willdean** [comment]
This exception in the log:

```2017-11-19 11:05:02.478 -05:00 [Error] Error caught in GitController
System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Bonobo.Git.Server.GitAuthorizeAttribute.IsUserAuthorized(String authHeader, HttpContextBase httpContext)
   at Bonobo.Git.Server.GitAuthorizeAttribute.OnAuthorization(AuthorizationContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
```

Suggests that there's something strange about the `Authoriziation` header which is being sent by the client (or at least, received by the server - perhaps something in between is meddling).  This header should look something like `Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==`, and Bonobo attempts to base-64 decode the last bit- in your case it seems that's failing.

Are you able to run a client (preferably  just command-line Git) on the same machine as Bonobo, and if so, are you able to run something like Fiddler to see what the auth header actually looks like?

**Comment by jbdicarlo** [comment]
I ran command line git on the server running Bonobo and got the same error, when I ran Fiddler I can't for the life of me get it to actually pick up any traffic from git. I tried it on the IIS box and on my local machine and picked up nothing from Git Bash, Git in cmd or Git in Brackets. 

The most I was able to get was doing the "wrong" thing and trying to open the git URL in IE which did get me a similar 500 response in Fiddler. I got a couple 401 Unauthorized from IIS before I got the 500 error with the same System.FormatException, so maybe the cause is IIS? It didn't actually render the error page, just the 500 exception, but I was able to see the HTML in Fiddler from the 401: "The authenticated user does not have access to a resource needed to process the request" 

It's entirely possible I've overlooked something during setup and will inevitably look silly for it. :stuck_out_tongue:

**Comment by willdean** [comment]
@jbdicarlo Thanks for persisting with this - sometimes Fiddler is tricky with local stuff.  

An alternative is, from the command line, to run `set GIT_CURL_VERBOSE=1` before you run the git command.  Then you should get a load of trace, which will include the `Authorization: Basic ...base64 string...` header.   There should be at least two connections - the first one will fail with a 401 Unauthorized, then the second one will have the `Authorization:` header in it.

If you have access to some means to decode a base64 string, then you should see if it makes sense.  **Don't post it here, because even though it looks like nonsense it's actually your unencrypted username/password**

**Comment by jbdicarlo** [comment]
Does this seem like what we're looking for?

`````
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jbdicarlo>set GIT_CURL_VERBOSE=1

C:\Users\jbdicarlo>git clone http://web-server/Bonobo.Git.Server/Dashboard_Fr
ontEnd.git
Cloning into 'Dashboard_FrontEnd'...
* Couldn't find host web-server in the _netrc file; using defaults
* timeout on name lookup is not supported
*   Trying XX.XX.XX.XX...
* TCP_NODELAY set
* Connected to web-server XX.XX.XX.XX) port 80 (#0)
> GET /Bonobo.Git.Server/Dashboard_FrontEnd.git/info/refs?service=git-upload-pac
k HTTP/1.1
Host: web-server
User-Agent: git/2.13.1.windows.2
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Cache-Control: private
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-AspNetMvc-Version: 5.2
< WWW-Authenticate: Basic realm="Bonobo Git"
< X-AspNet-Version: 4.0.30319
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< Date: Mon, 20 Nov 2017 12:49:22 GMT
< Content-Length: 1293
<
* Connection #0 to host web-server left intact
Username for 'http://web-server': jbdicarlo
Password for 'http://jbdicarlo@web-server':
* Couldn't find host web-server in the _netrc file; using defaults
* Found bundle for host web-server: 0x41ad80 [can pipeline]
* timeout on name lookup is not supported
* Hostname web-server was found in DNS cache
*   Trying XX.XX.XX.XX...
* TCP_NODELAY set
* Connected to web-server (XX.XX.XX.XX) port 80 (#1)
> GET /Bonobo.Git.Server/Dashboard_FrontEnd.git/info/refs?service=git-upload-pac
k HTTP/1.1
Host: web-server
User-Agent: git/2.13.1.windows.2
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Cache-Control: private
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-AspNetMvc-Version: 5.2
< WWW-Authenticate: Basic realm="Bonobo Git"
< X-AspNet-Version: 4.0.30319
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< Date: Mon, 20 Nov 2017 12:49:38 GMT
< Content-Length: 1293
<
* Ignoring the response-body
* Connection #1 to host web-server left intact
* Issue another request to this URL: 'http://web-server/Bonobo.Git.Server/Das
hboard_FrontEnd.git/info/refs?service=git-upload-pack'
* Couldn't find host web-server in the _netrc file; using defaults
* Found bundle for host web-server: 0x41ad80 [can pipeline]
* Re-using existing connection! (#1) with host web-server
* Connected to web-server (XX.XX.XX.XX) port 80 (#1)
* Server auth using NTLM with user 'jbdicarlo'
> GET /Bonobo.Git.Server/Dashboard_FrontEnd.git/info/refs?service=git-upload-pac
k HTTP/1.1
Host: web-server
Authorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==
User-Agent: git/2.13.1.windows.2
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< WWW-Authenticate: NTLM *** BASE 64 REMOVED ***
< Date: Mon, 20 Nov 2017 12:49:38 GMT
< Content-Length: 341
<
* Ignoring the response-body
* Connection #1 to host web-server left intact
* Issue another request to this URL: 'http://web-server/Bonobo.Git.Server/Das
hboard_FrontEnd.git/info/refs?service=git-upload-pack'
* Couldn't find host web-server in the _netrc file; using defaults
* Found bundle for host web-server: 0x41ad80 [can pipeline]
* Re-using existing connection! (#1) with host web-server
* Connected to web-server (XX.XX.XX.XX) port 80 (#1)
* Server auth using NTLM with user 'jbdicarlo'
> GET /Bonobo.Git.Server/Dashboard_FrontEnd.git/info/refs?service=git-upload-pac
k HTTP/1.1
Host: web-server
Authorization: NTLM *** BASE 64 REMOVED ***
User-Agent: git/2.13.1.windows.2
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Cache-Control: private
< Content-Type: text/html
< Server: Microsoft-IIS/8.5
< X-AspNetMvc-Version: 5.2
< X-AspNet-Version: 4.0.30319
< WWW-Authenticate: Negotiate
* NTLM handshake rejected
* Authentication problem. Ignoring this.
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< Date: Mon, 20 Nov 2017 12:49:38 GMT
< Content-Length: 1293
<
* Connection #1 to host web-server left intact
fatal: Authentication failed for 'http://web-server/Bonobo.Git.Server/Dashboa
rd_FrontEnd.git/'

C:\Users\jbdicarlo>

**Comment by willdean** [comment]
Yes, thanks - it looks like an IIS problem - can you check the step on this page 
https://bonobogitserver.com/install/ marked "Configure Authentication"

It appears that IIS is asking the client to do NTLM rather than basic auth, and then Bonobo is being confused by that.

If you wanted to be doing Windows auth, then check out this page: https://bonobogitserver.com/windows-authentication/

**Comment by JasonVKGE** [comment]
The page for doing Windows auth makes no mention of changing the IIS configuration to "Enabled" (see screen shot). Is this also required?

![image](https://user-images.githubusercontent.com/23267222/33045680-55a0d4c4-ce13-11e7-86fc-d927fa0be9f4.png)

**Comment by larshg** [comment]
Windows authentication should be disabled in IIS.

**Comment by larshg** [comment]
Only enabled in the config file.
