### ISSUE TITLE
Active Directory -[Error] GetPrincipal Group with name

### ISSUE THREAD

**Issue by marttin-h** [jakubgarfield/Bonobo-Git-Server#826]
Please how to fix error ?
Thanks

```
2018-12-17 15:21:47.454 +01:00 [Error] GetPrincipal Group with name: Group_evyvoj
System.DirectoryServices.DirectoryServicesCOMException (0x80072020): An operations error occurred.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.GroupPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Bonobo.Git.Server.Helpers.ADHelper.GetPrincipalGroup(String name, GroupPrincipal& group)
2018-12-17 15:21:47.469 +01:00 [Error] AD: Failed to update users.
System.ArgumentException: Could not find principal group: Group_evyvoj
   at Bonobo.Git.Server.Helpers.ADHelper.GetPrincipalGroup(String name, GroupPrincipal& group)
   at Bonobo.Git.Server.Data.ADBackend.UpdateUsers()
```

**Comment by katerlol** [comment]
Since i recently stumbled across this aswell, what helped for me was to triplecheck the AppPool for my application which was wrongly set to LocalService. 
After i changed the identity to LocalSystem the error went away. 

**Open IIS > Apppools > rightclick on the used app pool > advanced settings > Change identity to LocalSystem**
