### ISSUE TITLE
Error 500/The directory name is invalid

### ISSUE THREAD

**Issue by tonibony** [jakubgarfield/Bonobo-Git-Server#851]
I have a problem: The access from remote git client to the only git repository served in my installation of Bonobo git server stopped working. Can anyone help me?

This is new installation of Bonobo git server on Windows 7 SP1, 32-bit, with IIS7 and .NET 4.8. I installed it the last week and it worked. The only change since then is that the machine was restarted,

Here are the errors I receive:

On the client:

`fatal: unable to access 'http://.../Bonobo.Git.Server/.../': The requested url returned error: 500`

On the server (extracted from C:\inetpub\wwwroot\Bonobo.Git.Server\App_Data\Logs):
```
[Error] Error caught in GitController
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bonobo.Git.Server.Git.GitService.GitServiceExecutor.ExecuteServiceByName(String correlationId, String repositoryName, String serviceName, ExecutionOptions options, Stream inStream, Stream outStream)
   at Bonobo.Git.Server.Controllers.GitController.<>c__DisplayClass23_0.<GetInfoRefs>b__0(Stream outStream)
   at Bonobo.Git.Server.Git.GitCmdResult.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

These errors are result from "git fetch", but I tried also pull and push and got the same errors.

The anonymous access to the repository is allowed.

While testing the problem, I deleted and re-created the repository using the Web interface of Bonobo git server (I have enough copies of this repo). The errors are exactly the same with the new repositroy.

**Comment by tonibony** [comment]
I have reinstalled the Bonobo Git Server in IIS and the problem disappeared.
